source 'https://github.com/CocoaPods/Specs.git'
pod 'iCarousel'
pod 'SVProgressHUD'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'JFParseFBFriends'
pod 'pop'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'Facebook-iOS-SDK', :inhibit_warnings => true
